<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container1lEu5VD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container1lEu5VD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container1lEu5VD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container1lEu5VD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container1lEu5VD\App_KernelDevDebugContainer([
    'container.build_hash' => '1lEu5VD',
    'container.build_id' => 'cb13ba40',
    'container.build_time' => 1580387583,
], __DIR__.\DIRECTORY_SEPARATOR.'Container1lEu5VD');
