<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJPx5nOO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJPx5nOO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJPx5nOO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJPx5nOO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJPx5nOO\App_KernelDevDebugContainer([
    'container.build_hash' => 'JPx5nOO',
    'container.build_id' => '7d23518b',
    'container.build_time' => 1580409179,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJPx5nOO');
