<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4IrO5xi\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4IrO5xi/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4IrO5xi.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4IrO5xi\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container4IrO5xi\App_KernelDevDebugContainer([
    'container.build_hash' => '4IrO5xi',
    'container.build_id' => 'ed8e61b1',
    'container.build_time' => 1580474258,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4IrO5xi');
